name: CI - PR

on:
  pull_request_target:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint
      - uses: ArtiomTr/jest-coverage-report-action@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v5.1.0
        with:
          start: npm run dev
          wait-on: http://localhost:8000
        env:
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PRODUCTION_HOST: ${{ secrets.DATABASE_PRODUCTION_HOST }}
          DATABASE_DEVELOPMENT_HOST: ${{ secrets.DATABASE_DEVELOPMENT_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
